from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.core.models import BaseModel


class Character(BaseModel):
    """Character Model.

    Characters can be generated by the user. Characters will be used for
    generating fanfictions.

    """

    class GenderChoice(models.TextChoices):
        """Gender list for characters."""

        MALE = "male", _("Male")
        FEMALE = "female", _("Female")
        OTHER = "other", _("Other")

    name = models.CharField(
        verbose_name=_("Name"),
        max_length=50,
    )
    age = models.PositiveIntegerField(
        verbose_name=_("Age"),
    )
    gender = models.CharField(
        verbose_name=_("Gender"),
        max_length=6,
        choices=GenderChoice.choices,
        default=GenderChoice.MALE,
    )
    description = models.TextField(
        verbose_name=_("Description"),
    )
    user = models.ForeignKey(
        to="users.User",
        on_delete=models.CASCADE,
        related_name="characters",
        verbose_name=_("User"),
    )
    universe = models.ForeignKey(
        to="characters.Universe",
        on_delete=models.CASCADE,
        related_name="characters",
        verbose_name=_("Universe"),
    )

    class Meta:
        verbose_name = _("Character")
        verbose_name_plural = _("Characters")
        constraints = (
            models.UniqueConstraint(
                fields=("name", "universe"),
                name="unique_name_universe",
            ),
        )

    def __str__(self) -> str:
        return self.name
