# Generated by Django 4.1.7 on 2023-04-20 03:54

from django.db import migrations, models
from django.utils import timezone


def set_publication_date(apps, schema_editor):
    """Set publication date for published fanfictions."""
    Fanfiction = apps.get_model("fanfictions", "Fanfiction")
    Fanfiction.objects.filter(
        is_published=True,
    ).update(
        publication_date=timezone.now().date(),
    )


def unset_publication_date(apps, schema_editor):
    """Unset publication date for published fanfictions."""
    Fanfiction = apps.get_model("fanfictions", "Fanfiction")
    Fanfiction.objects.filter(
        is_published=True,
    ).update(
        publication_date=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('fanfictions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfiction',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Designates whether the fanfiction is published or not.', verbose_name='Publication status'),
        ),
        migrations.RenameField(
            model_name='fanfiction',
            old_name='is_public',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='fanfiction',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.RunPython(set_publication_date, unset_publication_date),
    ]
