# Generated by Django 4.1.7 on 2023-04-21 08:32

from django.db import migrations

GENRE_NAMES = [
    "Adventure",
    "Comedy",
    "Drama",
    "Crime",
    "Horror",
    "Fantasy",
    "Romance",
    "Thriller",
    "Family",
    "War",
    "Documentary",
    "Western",
]


def fill_in_genres(apps, schema_editor):
    """Provide initial data for `Genre` model."""
    Genre = apps.get_model("fanfictions", "Genre")
    Genre.objects.bulk_create(
        [
            Genre(name=genre_name) for genre_name in GENRE_NAMES
        ],
        ignore_conflicts=True,
    )


def remove_genres(apps, schema_editor):
    """Remove initial data of `Genre` model."""
    Genre = apps.get_model("fanfictions", "Genre")
    Genre.objects.filter(name__in=GENRE_NAMES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('fanfictions', '0002_rename_fanfiction_is_public_fanfiction_is_published_and_more'),
    ]

    operations = [
        migrations.RunPython(code=fill_in_genres, reverse_code=remove_genres),
    ]
